name: Build maven

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          cache: maven

      - name: Maven verify
        run: mvn -B --no-transfer-progress verify --file pom.xml

