name: Npm build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"

jobs:
  build-sources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{inputs.node-version}}

      - name: Dependency caching
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.npm
          key: v1-${{ runner.os }}-build-${{ hashFiles ('**/package-lock.json')}}
          restore-keys: |
            v1-${{ runner.os }}-build-
            
      - name: Install dependencies
        run: npm ci --ignore-scripts
        
      - name: Build
        run: npm run build
        
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: app
          path: |
            node_modules/
            .next
            public
            package.json
